### ISSUE TITLE
More than one source directory?

### ISSUE THREAD

**Issue by Wikinaut** [thomas-mc-work/rtb-wrapper#3]
Is it, would it be possible, to define a **list** of directories to be backed-up?

e.g. ```SOURCE="/home /usr /etc /work /srv"```

which then would "land" in corresponding subdirectories below the (example) ```TARGET="/mnt/backup/computer3"``` directory.

**Comment by thomas-mc-work** [comment]
Unfortunately that's not possible for now as this project is only a wrapper around [rsync-time-backup](https://github.com/laurent22/rsync-time-backup) and is thus coupled to the features and shortcomings of it. I'd also love to have this feature though!

b.t.w. [here](https://github.com/laurent22/rsync-time-backup/issues/112) the answer would be also *no*.

And here is another issue about the same topic: https://github.com/laurent22/rsync-time-backup/issues/94

**Comment by Wikinaut** [comment]
As a workaround, on Linux systems I suggest to artificially create a pseudo structure with symbolic links to the directories like mentioned under a single path like \tobebackedup and to pass this as "source" argument.

Also proposed here https://github.com/laurent22/rsync-time-backup/issues/94#issuecomment-345355041 .
